#!/usr/bin/with-contenv bash
# shellcheck shell=bash

declare -a options
declare serial_number
declare rtl_device

echo "Starting rtl_tcp..."

options+=(-a 127.0.0.1)

rtl_num_devices=$(/usr/bin/rtl_eeprom 2>&1 >/dev/null | grep "Found [0-9][0-9]*" | sed -E 's/.*([0-9]+).*/\1/')
if [ $rtl_num_devices ]; then
    for i in $(seq 1 $rtl_num_devices); do
        rtl_device=$((i - 1))
        rtl_serial=$(/usr/bin/rtl_eeprom -d$rtl_device 2>&1 >/dev/null | grep "Serial number\:" | sed -E 's/Serial number:[[:blank:]]+//')
        if [ "$1" == "$rtl_serial" ]; then
            echo "[-] Found RTL-SDR device number ${rtl_device} with serial number ${serial_number}"
            options+=("-d ${rtl_device}")
        else
            echo "[!] Failed to find RTL-SDR device with serial number ${serial_number}"
        fi
    done
else
    echo "[!] Failed to find any RTL-SDR devices!"
fi

exec /usr/bin/rtl_tcp "${options[@]}"
